In [30]:
import numpy as np
import pandas as pd
import yfinance as yf
import sklearn.metrics as mt 
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.cluster import KMeans
from sklearn.metrics import confusion_matrix
from sklearn import metrics
from sklearn.naive_bayes import GaussianNB  
from sklearn.metrics import accuracy_score


In [41]:
credit = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/credit-screening/crx.data', header=None)
fn = {'+': 1, '-': 0}

X = credit.replace('?',0).iloc[:,[1,2,7,10,14]]
y = credit.iloc[:,15].map(lambda x: fn.get(x,0))

In [32]:
credit

0      1       2  3  4   5   6     7  8  9   10 11 12     13   14 15
0    b  30.83   0.000  u  g   w   v  1.25  t  t   1  f  g  00202    0  +
1    a  58.67   4.460  u  g   q   h  3.04  t  t   6  f  g  00043  560  +
2    a  24.50   0.500  u  g   q   h  1.50  t  f   0  f  g  00280  824  +
3    b  27.83   1.540  u  g   w   v  3.75  t  t   5  t  g  00100    3  +
4    b  20.17   5.625  u  g   w   v  1.71  t  f   0  f  s  00120    0  +
..  ..    ...     ... .. ..  ..  ..   ... .. ..  .. .. ..    ...  ... ..
685  b  21.08  10.085  y  p   e   h  1.25  f  f   0  f  g  00260    0  -
686  a  22.67   0.750  u  g   c   v  2.00  f  t   2  t  g  00200  394  -
687  a  25.25  13.500  y  p  ff  ff  2.00  f  t   1  t  g  00200    1  -
688  b  17.92   0.205  u  g  aa   v  0.04  f  f   0  f  g  00280  750  -
689  b  35.00   3.375  u  g   c   h  8.29  f  f   0  t  g  00000    0  -

[690 rows x 16 columns]

In [42]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

Splitting the data into training and test set.

In [43]:
model = LogisticRegression(random_state=1).fit(X_train, y_train)

y_predict = model.predict(X_test)

A logistic regression model with a 0.75 test size.

In [44]:
cnf_matrix = metrics.confusion_matrix(y_test, y_predict)

accuracy = mt.accuracy_score(y_test, y_predict)

print(cnf_matrix)

print(accuracy)

[[79 12]
 [35 47]]
0.7283236994219653


In [45]:
X_train, X_test, y_train, y_test = train_test_split(X,y,train_size=0.75)

model = LogisticRegression(max_iter=2000)
model.fit(X_train,y_train)
print(model.score(X_test,y_test))
y_predict = model.predict(X_test)
confusion_matrix(y_test,y_predict)

0.7514450867052023


array([[77,  9],
       [34, 53]], dtype=int64)

In [46]:
X_train, X_test, y_train, y_test = train_test_split(X,y,train_size=0.75)

model = LogisticRegression(max_iter=3000)
model.fit(X_train,y_train)
print(model.score(X_test,y_test))
y_predict = model.predict(X_test)
confusion_matrix(y_test,y_predict)

0.7514450867052023


array([[86, 11],
       [32, 44]], dtype=int64)

When we increase iteration count, we get better results.

In [18]:
model = KMeans(n_clusters = 2).fit(X_train, y_train)
predictions =  model.predict(X_test)


cm = confusion_matrix(y_test, predictions)

import sklearn.metrics as mt 

accuracy = mt.accuracy_score(y_test, predictions)
accuracy

0.5317919075144508

Since K-means is an unsupervised learning algorithm, most likely we will get a worse result than other models. We can observe that here as well.

In [24]:
classifier = GaussianNB()  
classifier.fit(X_train, y_train) 
y_pred = classifier.predict(X_test)
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred) 


0.7572254335260116

Gaussian Naive Byes algorithm